### ISSUE TITLE
Page Element to Control Playback Speed

### ISSUE THREAD

**Issue by marquerere** [TheNunoGomes/youtube-accelerator#1]
# Feature Request

Right now it can feel a little cumbersome to have to open the extension every time you wish to adjust the playback speed. Having an extension control directly on the page near the usual Youtube controls would benefit the user experience substantially.

### Current Behavior
- Open the extension in order to change the playback speed.

### Suggested Behavior
- Change the playback speed directly through an element on the page.

**Comment by TheNunoGomes** [comment]
Thanks for the suggestion @marquerere, it has been implemented.
